M48
; DRILL file KiCad 10.0.3 date 2026-08-06T18:36:45
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-06T18:36:45+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X133.195Y-17.11
X133.195Y-22.89
T2
X5.0Y-5.0
X5.0Y-65.0
X135.0Y-5.0
X135.0Y-65.0
M30
